# -*- coding: utf-8 -*-

OVERVIEW_LEFT_PANE_WIDTH = 200
OVERVIEW_LEFT_PANE_HEIGHT = 600
OVERVIEW_CENTER_PANE_WIDTH = 600
OVERVIEW_CENTER_PANE_HEIGHT = 600
OVERVIEW_TRACK_BOX_HEIGHT = 128
OVERVIEW_NUMBER_OF_TRACKS = 16
TRACK_RIGHT_EXTEND = 300
OVERVIEW_TIME_STEP_WIDTH = 4