# -*- coding: utf-8 -*-

OVERVIEW_LEFT_PANE_WIDTH = 200
OVERVIEW_LEFT_PANE_HEIGHT = 600
OVERVIEW_CENTER_PANE_WIDTH = 600
OVERVIEW_CENTER_PANE_HEIGHT = 600
OVERVIEW_TRACK_BOX_HEIGHT = 128
OVERVIEW_NUMBER_OF_TRACKS = 16
TRACK_RIGHT_EXTEND = 300
OVERVIEW_TIME_STEP_WIDTH = 4
MAX_POLY = 5
EDITING_CENTER_PANE_WIDTH = 600
EDITING_CENTER_PANE_HEIGHT = 600
GRID_PIXELS_PER_SEMINOTE = 12
GRID_WHITE_KEY_COLOR = "#444"
GRID_BLACK_KEY_COLOR = "#111"
GRID_MIDDLE_C_COLOR = "#777"
GRID_KEY_BORDER_COLOR = "#222"
GRID_PIXELS_PER_TIMESTEP = 16
TRACK_COLORS = ["#a00", "#0a0", "#00a", "#aa0", "#a0a", "#0aa"]